name: push and test

run-name: Testing ${{github.actor}} with ${{github.action}}

on: [push]

jobs:

  setup:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: install node
      
        uses: actions/setup-node@v4

        with:
          node-version: 18
          cache: 'npm'

      - name: install app

        run: make setup

      - name: Checkout branch

        uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities

        uses: snyk/actions/node@master

        env:          
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        with:
          args: --severity-threshold=high

      - name: run linter

        run: make lint

      - name: run tests

        run: make test